ROUND_OF_32_STRUCTURE = [
    {"match_id": 73, "team_a_slot": "2A", "team_b_slot": "2B"},
    {"match_id": 74, "team_a_slot": "1E", "team_b_slot": "3_ABCDF"},
    {"match_id": 75, "team_a_slot": "1F", "team_b_slot": "2C"},
    {"match_id": 76, "team_a_slot": "1C", "team_b_slot": "2F"},
    {"match_id": 77, "team_a_slot": "1I", "team_b_slot": "3_CDFGH"},
    {"match_id": 78, "team_a_slot": "2E", "team_b_slot": "2I"},
    {"match_id": 79, "team_a_slot": "1A", "team_b_slot": "3_CEFHI"},
    {"match_id": 80, "team_a_slot": "1L", "team_b_slot": "3_EHIJK"},
    {"match_id": 81, "team_a_slot": "1D", "team_b_slot": "3_BEFIJ"},
    {"match_id": 82, "team_a_slot": "1G", "team_b_slot": "3_AEHIJ"},
    {"match_id": 83, "team_a_slot": "2K", "team_b_slot": "2L"},
    {"match_id": 84, "team_a_slot": "1H", "team_b_slot": "2J"},
    {"match_id": 85, "team_a_slot": "1B", "team_b_slot": "3_EFGIJ"},
    {"match_id": 86, "team_a_slot": "1J", "team_b_slot": "2H"},
    {"match_id": 87, "team_a_slot": "1K", "team_b_slot": "3_DEIJL"},
    {"match_id": 88, "team_a_slot": "2D", "team_b_slot": "2G"},
]